   pipeline:
       name: SamplePipelineForTraining
       steps:
           TrainStep:
               python_script_step:
                   name: "PythonScriptStep"
                   script_name: "train.py"
                   allow_reuse: True
                   source_directory: "."
               runconfig: 'aml_config/train.runconfig'
               outputs:
                   result:
                       destination: Output
                       datastore: workspaceblobstore
                       type: mount
        
        
